package handlers

import "backend/internal/models"

var mockShops = []models.Shop{
	{
		ID:                 1,
		Name:               "Tech Haven",
		Logo:               "https://picsum.photos/seed/shop1logo/150/150",
		Rating:             4.8,
		DeliveryCharge:     15.0,
		DeliveryChargeType: "2-3 Days",
		Banner:             "https://picsum.photos/seed/shop1banner/800/400",
		TotalProducts:      120,
		TotalCategories:    5,
		ShopStatus:         "OPEN",
		TotalReviews:       "500",
	},
	{
		ID:                 2,
		Name:               "Fashion Forward",
		Logo:               "https://picsum.photos/seed/shop2logo/150/150",
		Rating:             4.5,
		DeliveryCharge:     10.0,
		DeliveryChargeType: "3-5 Days",
		Banner:             "https://picsum.photos/seed/shop2banner/800/400",
		TotalProducts:      350,
		TotalCategories:    8,
		ShopStatus:         "OPEN",
		TotalReviews:       "1200",
	},
	{
		ID:                 3,
		Name:               "Home Essentials",
		Logo:               "https://picsum.photos/seed/shop3logo/150/150",
		Rating:             4.7,
		DeliveryCharge:     20.0,
		DeliveryChargeType: "1-2 Days",
		Banner:             "https://picsum.photos/seed/shop3banner/800/400",
		TotalProducts:      80,
		TotalCategories:    4,
		ShopStatus:         "OPEN",
		TotalReviews:       "300",
	},
	{
		ID:                 4,
		Name:               "Sports Pro",
		Logo:               "https://picsum.photos/seed/shop4logo/150/150",
		Rating:             4.9,
		DeliveryCharge:     12.0,
		DeliveryChargeType: "2-4 Days",
		Banner:             "https://picsum.photos/seed/shop4banner/800/400",
		TotalProducts:      150,
		TotalCategories:    6,
		ShopStatus:         "OPEN",
		TotalReviews:       "850",
	},
	{
		ID:                 5,
		Name:               "Beauty Boutique",
		Logo:               "https://picsum.photos/seed/shop5logo/150/150",
		Rating:             4.6,
		DeliveryCharge:     5.0,
		DeliveryChargeType: "3-4 Days",
		Banner:             "https://picsum.photos/seed/shop5banner/800/400",
		TotalProducts:      200,
		TotalCategories:    3,
		ShopStatus:         "OPEN",
		TotalReviews:       "450",
	},
}

var mockProducts = []models.Product{
	// Tech Haven Products
	{
		ID:               1,
		Name:             "iPhone 15 Pro",
		ShortDescription: "The ultimate iPhone.",
		Description:      "The iPhone 15 Pro features a titanium design, A17 Pro chip, and a 48MP Main camera. Ideally suited for professionals and creators.",
		Thumbnail:        "https://picsum.photos/seed/prod1/300/300",
		Thumbnails: []models.Thumbnail{
			{ID: 1, Thumbnail: "https://picsum.photos/seed/prod1/300/300", URL: "", Type: "image"},
		},
		Images:             []string{},
		Price:              999.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.9,
		TotalReviews:       "150",
		TotalSold:          "500",
		Quantity:           50,
		IsFavorite:         false,
		Brand:              "Apple",
		Shop:               mockShops[0],
		Colors:             []models.Color{{ID: 1, Name: "Titanium", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 1, Name: "256GB", Price: 0}},
	},
	{
		ID:                 2,
		Name:               "MacBook Pro 14",
		Thumbnail:          "https://picsum.photos/seed/prod2/300/300",
		Price:              1999.0,
		DiscountPrice:      1899.0,
		DiscountPercentage: 5,
		Rating:             5.0,
		TotalReviews:       "80",
		TotalSold:          "200",
		Quantity:           20,
		IsFavorite:         true,
		Brand:              "Apple",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[0],
		Colors:             []models.Color{{ID: 2, Name: "Space Gray", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 2, Name: "M3 Pro", Price: 0}},
	},
	{
		ID:                 3,
		Name:               "Sony WH-1000XM5",
		Thumbnail:          "https://picsum.photos/seed/prod3/300/300",
		Price:              399.0,
		DiscountPrice:      349.0,
		DiscountPercentage: 12,
		Rating:             4.8,
		TotalReviews:       "300",
		TotalSold:          "1000",
		Quantity:           100,
		IsFavorite:         false,
		Brand:              "Sony",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[0],
		Colors:             []models.Color{{ID: 3, Name: "Black", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 4,
		Name:               "Samsung Galaxy S24",
		Thumbnail:          "https://picsum.photos/seed/prod4/300/300",
		Price:              899.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.7,
		TotalReviews:       "120",
		TotalSold:          "400",
		Quantity:           60,
		IsFavorite:         false,
		Brand:              "Samsung",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[0],
		Colors:             []models.Color{{ID: 4, Name: "Black", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 3, Name: "128GB", Price: 0}},
	},

	// Fashion Forward Products
	{
		ID:                 5,
		Name:               "Classic Leather Jacket",
		Thumbnail:          "https://picsum.photos/seed/prod5/300/300",
		Price:              150.0,
		DiscountPrice:      120.0,
		DiscountPercentage: 20,
		Rating:             4.6,
		TotalReviews:       "50",
		TotalSold:          "150",
		Quantity:           30,
		IsFavorite:         true,
		Brand:              "Generic",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[1],
		Colors:             []models.Color{{ID: 5, Name: "Black", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 4, Name: "M", Price: 0}, {ID: 5, Name: "L", Price: 0}},
	},
	{
		ID:                 6,
		Name:               "Denim Jeans",
		Thumbnail:          "https://picsum.photos/seed/prod6/300/300",
		Price:              60.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.5,
		TotalReviews:       "200",
		TotalSold:          "800",
		Quantity:           150,
		IsFavorite:         false,
		Brand:              "Levis",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[1],
		Colors:             []models.Color{{ID: 6, Name: "Blue", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 6, Name: "32", Price: 0}, {ID: 7, Name: "34", Price: 0}},
	},
	{
		ID:                 7,
		Name:               "Running Sneakers",
		Thumbnail:          "https://picsum.photos/seed/prod7/300/300",
		Price:              120.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.8,
		TotalReviews:       "400",
		TotalSold:          "1200",
		Quantity:           80,
		IsFavorite:         false,
		Brand:              "Nike",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[1],
		Colors:             []models.Color{{ID: 7, Name: "Red", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 8, Name: "42", Price: 0}, {ID: 9, Name: "43", Price: 0}},
	},
	{
		ID:                 8,
		Name:               "Cotton T-Shirt",
		Thumbnail:          "https://picsum.photos/seed/prod8/300/300",
		Price:              25.0,
		DiscountPrice:      20.0,
		DiscountPercentage: 20,
		Rating:             4.4,
		TotalReviews:       "150",
		TotalSold:          "600",
		Quantity:           200,
		IsFavorite:         false,
		Brand:              "H&M",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[1],
		Colors:             []models.Color{{ID: 8, Name: "White", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 4, Name: "M", Price: 0}},
	},

	// Home Essentials Products
	{
		ID:                 9,
		Name:               "Espresso Machine",
		Thumbnail:          "https://picsum.photos/seed/prod9/300/300",
		Price:              250.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.7,
		TotalReviews:       "90",
		TotalSold:          "300",
		Quantity:           40,
		IsFavorite:         true,
		Brand:              "Breville",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[2],
		Colors:             []models.Color{{ID: 9, Name: "Silver", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 10,
		Name:               "Robot Vacuum",
		Thumbnail:          "https://picsum.photos/seed/prod10/300/300",
		Price:              300.0,
		DiscountPrice:      250.0,
		DiscountPercentage: 16,
		Rating:             4.5,
		TotalReviews:       "60",
		TotalSold:          "180",
		Quantity:           25,
		IsFavorite:         false,
		Brand:              "Roomba",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[2],
		Colors:             []models.Color{{ID: 3, Name: "Black", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 11,
		Name:               "Desk Lamp",
		Thumbnail:          "https://picsum.photos/seed/prod11/300/300",
		Price:              45.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.3,
		TotalReviews:       "40",
		TotalSold:          "100",
		Quantity:           100,
		IsFavorite:         false,
		Brand:              "Ikea",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[2],
		Colors:             []models.Color{{ID: 8, Name: "White", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 12,
		Name:               "Cotton Bath Towel",
		Thumbnail:          "https://picsum.photos/seed/prod12/300/300",
		Price:              20.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.6,
		TotalReviews:       "110",
		TotalSold:          "500",
		Quantity:           150,
		IsFavorite:         false,
		Brand:              "Generic",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[2],
		Colors:             []models.Color{{ID: 10, Name: "Beige", Price: 0}},
		Sizes:              []models.SizeModel{},
	},

	// Sports Pro Products
	{
		ID:                 13,
		Name:               "Yoga Mat",
		Thumbnail:          "https://picsum.photos/seed/prod13/300/300",
		Price:              30.0,
		DiscountPrice:      25.0,
		DiscountPercentage: 16,
		Rating:             4.8,
		TotalReviews:       "200",
		TotalSold:          "800",
		Quantity:           100,
		IsFavorite:         false,
		Brand:              "Lululemon",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[3],
		Colors:             []models.Color{{ID: 11, Name: "Purple", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 14,
		Name:               "Dumbbell Set",
		Thumbnail:          "https://picsum.photos/seed/prod14/300/300",
		Price:              80.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.7,
		TotalReviews:       "150",
		TotalSold:          "400",
		Quantity:           40,
		IsFavorite:         false,
		Brand:              "Bowflex",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[3],
		Colors:             []models.Color{{ID: 3, Name: "Black", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 15,
		Name:               "Tennis Racket",
		Thumbnail:          "https://picsum.photos/seed/prod15/300/300",
		Price:              120.0,
		DiscountPrice:      100.0,
		DiscountPercentage: 16,
		Rating:             4.9,
		TotalReviews:       "80",
		TotalSold:          "250",
		Quantity:           30,
		IsFavorite:         true,
		Brand:              "Wilson",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[3],
		Colors:             []models.Color{{ID: 7, Name: "Red", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 16,
		Name:               "Protein Powder",
		Thumbnail:          "https://picsum.photos/seed/prod16/300/300",
		Price:              50.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.5,
		TotalReviews:       "300",
		TotalSold:          "1000",
		Quantity:           200,
		IsFavorite:         false,
		Brand:              "Optimum Nutrition",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[3],
		Colors:             []models.Color{{ID: 12, Name: "Chocolate", Price: 0}},
		Sizes:              []models.SizeModel{{ID: 10, Name: "2lb", Price: 0}},
	},

	// Beauty Boutique Products
	{
		ID:                 17,
		Name:               "Luxury Perfume",
		Thumbnail:          "https://picsum.photos/seed/prod17/300/300",
		Price:              90.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.8,
		TotalReviews:       "120",
		TotalSold:          "300",
		Quantity:           60,
		IsFavorite:         true,
		Brand:              "Chanel",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[4],
		Colors:             []models.Color{},
		Sizes:              []models.SizeModel{{ID: 11, Name: "50ml", Price: 0}},
	},
	{
		ID:                 18,
		Name:               "Face Moisturizer",
		Thumbnail:          "https://picsum.photos/seed/prod18/300/300",
		Price:              35.0,
		DiscountPrice:      30.0,
		DiscountPercentage: 14,
		Rating:             4.6,
		TotalReviews:       "200",
		TotalSold:          "600",
		Quantity:           100,
		IsFavorite:         false,
		Brand:              "CeraVe",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[4],
		Colors:             []models.Color{},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 19,
		Name:               "Matte Lipstick",
		Thumbnail:          "https://picsum.photos/seed/prod19/300/300",
		Price:              25.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.5,
		TotalReviews:       "300",
		TotalSold:          "900",
		Quantity:           150,
		IsFavorite:         false,
		Brand:              "MAC",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[4],
		Colors:             []models.Color{{ID: 7, Name: "Red", Price: 0}},
		Sizes:              []models.SizeModel{},
	},
	{
		ID:                 20,
		Name:               "Shampoo",
		Thumbnail:          "https://picsum.photos/seed/prod20/300/300",
		Price:              15.0,
		DiscountPrice:      0,
		DiscountPercentage: 0,
		Rating:             4.3,
		TotalReviews:       "150",
		TotalSold:          "700",
		Quantity:           200,
		IsFavorite:         false,
		Brand:              "Pantene",
		Thumbnails:         []models.Thumbnail{},
		Images:             []string{},
		Shop:               mockShops[4],
		Colors:             []models.Color{},
		Sizes:              []models.SizeModel{{ID: 12, Name: "500ml", Price: 0}},
	},
}
