// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnwkduK9tqESOOZI_-MemybQ4CEJoimoY',
    appId: '1:253369840347:android:e173c61723fcb1ae49d2fe',
    messagingSenderId: '253369840347',
    projectId: 'ready-ecommerce',
    storageBucket: 'ready-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuH9hk9WcmrdbOQtYtcAF_XTjYpxveep0',
    appId: '1:253369840347:ios:ad14ae85cdc8540749d2fe',
    messagingSenderId: '253369840347',
    projectId: 'ready-ecommerce',
    storageBucket: 'ready-ecommerce.firebasestorage.app',
    androidClientId: '253369840347-ro95uv71lv9a0ehnclntuhjk5f13jl1e.apps.googleusercontent.com',
    iosClientId: '253369840347-jn11cep1csb4d1vlmb5frgbkn33jh98t.apps.googleusercontent.com',
    iosBundleId: 'com.readyecommerce.apps',
  );
}
